development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # url: redis://pub-redis-11625.us-east-1-3.7.ec2.redislabs.com:11625/
  url: redis://redistogo:62fca9b402fd3a6dd43088ae0c6bdc7b@viperfish.redistogo.com:11422/
